<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sdjseoog"
 *
 * Auto generated by Extension Builder 2014-12-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'SDJ TQ SEO Open Graph',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Pascal Bremmer',
	'author_email' => 'pascal@soup-du-jour.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.1',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);