<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sdjhfgkd20links"
 *
 * Auto generated by Extension Builder 2016-01-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'KD 2.0 Links',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Pascal Bremmer',
	'author_email' => 'pascal@soup-du-jour.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);